# CakesController.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 1st December 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class CakesController < ApplicationController

  before_filter :logged_in_required
  before_filter :manager_required
  before_filter :admin_required, :only => "destroy"
  
  def index
    # GET /cakes
    # GET /cakes.json
    @cakes = Cake.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cakes }
    end
  end

  def show
    # GET /cakes/1
    # GET /cakes/1.json
    @cake = Cake.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cake }
    end
  end

  def new
    # GET /cakes/new
    # GET /cakes/new.json
    @cake = Cake.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cake }
    end
  end

  def edit
    # GET /cakes/1/edit
    @cake = Cake.find(params[:id])
  end

  def create
    # POST /cakes
    # POST /cakes.json
    @cake = Cake.new(params[:cake])

    respond_to do |format|
      if @cake.save
        format.html { redirect_to @cake, notice: 'Cake was successfully created.' }
        format.json { render json: @cake, status: :created, location: @cake }
      else
        format.html { render action: "new" }
        format.json { render json: @cake.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # PUT /cakes/1
    # PUT /cakes/1.json
    @cake = Cake.find(params[:id])

    respond_to do |format|
      if @cake.update_attributes(params[:cake])
        format.html { redirect_to @cake, notice: 'Cake was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cake.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # DELETE /cakes/1
    # DELETE /cakes/1.json
    @cake = Cake.find(params[:id])
    @cake.destroy

    respond_to do |format|
      format.html { redirect_to cakes_url }
      format.json { head :no_content }
    end
  end

end