# ProductImagesController.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ProductImagesController < ApplicationController

  before_filter :logged_in_required
  before_filter :manager_required
  
  def index
    # GET /product_images
    # GET /product_images.json
    @product_images = ProductImage.all

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @product_images }
    end
  end

  def show
    # GET /product_images/1
    # GET /product_images/1.json
    @product_image = ProductImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @product_image }
    end
  end

  def new
    # GET /product_images/new
    # GET /product_images/new.json
    @product_image = ProductImage.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @product_image }
    end
  end

  def edit
    # GET /product_images/1/edit
    @product_image = ProductImage.find(params[:id])
  end

  def create
    # POST /product_images
    # POST /product_images.json
    @product_image = ProductImage.new(params[:product_image])

    respond_to do |format|
      if @product_image.save
        format.html { redirect_to @product_image, notice: 'Product image was successfully created.' }
        #format.json { render json: @product_image, status: :created, location: @product_image }
      else
        format.html { render action: "new" }
        #format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # PUT /product_images/1
    # PUT /product_images/1.json
    @product_image = ProductImage.find(params[:id])

    respond_to do |format|
      if @product_image.update_attributes(params[:product_image])
        format.html { redirect_to @product_image, notice: 'Product image was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # DELETE /product_images/1
    # DELETE /product_images/1.json
    @product_image = ProductImage.find(params[:id])
    @product_image.destroy

    respond_to do |format|
      format.html { redirect_to product_images_url }
      #format.json { head :no_content }
    end
  end

end