# ProductsController.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
# Modified by Julian Arnold (12111333) starting 12th November 2012.
#
# Note 1:  This was based on a solution from Stack Overflow:
#          http://stackoverflow.com/questions/13481673/activerecord-find-by-number-of-associated-records
#          Accessed on 1-Dec-2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ProductsController < ApplicationController

  before_filter :logged_in_required
  before_filter :manager_required
  before_filter :admin_required, :only => :destroy
  before_filter :get_variables
  
  def index
    # GET /products
    # GET /products.json
    @products = Product.paginate(:include => :product_category, :order => "product_categories.running_order, products.running_order",
                                 :per_page => 15, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @products }
    end
  end

  def show
    # GET /products/1
    # GET /products/1.json
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @product }
    end
  end

  def new
    # GET /products/new
    # GET /products/new.json
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @product }
    end
  end

  def edit
    # GET /products/1/edit
    @product = Product.find(params[:id])
  end

  def create
    # POST /products
    # POST /products.json
    @product = Product.new(params[:product])
    @product.created_by = current_user.id
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        #format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        #format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # PUT /products/1
    # PUT /products/1.json
    @product = Product.find(params[:id])
    params[:product][:updated_by] = current_user.id
    
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # DELETE /products/1
    # DELETE /products/1.json
    @product = Product.find(params[:id])
    if @product.product_prices.count == 0 and @product.product_images.count == 0 and @product.shopping_cart_items.count == 0
      @product.destroy
      flash[:notice] = "Product has been deleted successfully."
    else
      flash[:notice] = "Product could not be deleted."
    end

    respond_to do |format|
      format.html { redirect_to products_url }
      #format.json { head :no_content }
    end
  end
  
  def link_image
    #Parameters: {"product_id"=>"456", "image_id"=>"123", "commit"=>"Add"}
    @product = Product.find(params[:product_id].to_i)
    image = Image.find(params[:image_id].to_i)
    if image and @product
      last_pi = ProductImage.find(:first, :conditions => ["product_id = ?", @product.id], :order => "running_order DESC")
      pi = @product.product_images.new
      pi.image_id = image.id
      if last_pi
        pi.running_order = last_pi.running_order + 100
      else
        pi.running_order = 100
      end
      if pi.save
        flash[:notice] = "Image has been successfully linked to this product"
      else
        flash[:notice] = "Image was NOT linked to this product - something went wrong."
      end
      redirect_to @product
    end
  end
  
  private
  
  def get_variables
    @product_categories = ProductCategory.all(order: "running_order, name")
    @options_lists = OptionsList.all(order: "name")
    @special_occasions = SpecialOccasion.all(order: "running_order, name")
    @currencies = Currency.all(conditions: ["active = ?", true], order: "running_order")
    @unallocated_images = Image.all(:include => 'product_images', :conditions => ["base_product = ? and product_images.id IS NULL", true]) # see Note 1 above.
  end

end