# Cake.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 1st December 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class Cake < ActiveRecord::Base
  attr_accessible :shopping_cart_id, :based_on_finished_product_id, :cake_required_at, :confectioners_notes, :general_description_from_customer, :name_to_appear_on_cake, :production_quotum_id, :special_occasion, :weekday

  belongs_to  :production_quotum
  belongs_to  :shopping_cart
  belongs_to  :finished_product,
                :class_name => "FinishedProduct",
                :foreign_key => "based_on_finished_product_id"
                
  has_many    :shopping_cart_items
  
  validates_numericality_of :production_quotum_id, :shopping_cart_id
  validates_numericality_of :based_on_finished_product_id, :allow_nil => true
  validates_presence_of :cake_required_at, :name_to_appear_on_cake, :special_occasion

  before_save :log_the_weekday
  before_save :set_production_quantum_id

  private

  def set_production_quantum_id
    pq = ProductionQuotum.first(:conditions => ["start_date <= ? and finish_date >= ?", cake_required_at.to_date, cake_required_at.to_date])
    if pq
      self.production_quotum_id = pq.id
    end
  end

  def log_the_weekday
    self.weekday = cake_required_at.wday
  end


end
