# Currency.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class Currency < ActiveRecord::Base
  attr_accessible :active, :currency_symbol, :full_name, :iso_code, :running_order
  
  has_many :pay_pal_transactions
  has_many :product_prices
  has_one  :general_setting,
           :class_name => "GeneralSetting",
           :foreign_key => "default_currency_id"
  
  validates_presence_of :currency_symbol, :full_name, :iso_code, :running_order
  validates_uniqueness_of :iso_code
  validates_uniqueness_of :full_name
  validates_numericality_of :running_order

end
