# Customer.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class Customer < ActiveRecord::Base
  attr_accessible :user_id, :postal_address, :contact_phone_number
  
  validates_presence_of :user_id
  validates_uniqueness_of :postal_address
  
  has_many :shopping_carts
  belongs_to :user
  
  def open_cart
    cart = shopping_carts.first(:include => "shopping_cart_status", :conditions => ["shopping_cart_statuses.active_cart = ?", true], :order => "shopping_carts.created_at ASC")
    if cart != nil
      return cart
    else
      return nil
    end
  end
  
end
