# FinishedProduct.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 24th November 2012.
#
# Note 1  Search attribute based on code demonstrated by Wesley Gorman
#         in NCI lecture, and subsequently modified by Dan Laffan.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class FinishedProduct < ActiveRecord::Base
  attr_accessible :product_name, :description, :typical_price, :special_occasion_id, :running_order, :available_for_purchase, :visible, :created_at
  
  belongs_to :special_occasion
  has_many   :finished_product_images, :order => "running_order"
  has_many   :finished_product_ingredients
  
  validates_presence_of :product_name, :description, :typical_price, :running_order
  validates_uniqueness_of :product_name
  validates_numericality_of :running_order
  validates_numericality_of :typical_price
  
  # See note 1 above
	def self.search(search_query)
		find(:all, :conditions => ['product_name LIKE ? or description LIKE ?', "%" + search_query + "%", "%" + search_query + "%"])
	end
	
	def can_be_bought
	  if available_for_purchase == true and finished_product_ingredients.count > 0
	    return true
    else
      return false
    end
  end
	
end
