# GeneralSetting.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class GeneralSetting < ActiveRecord::Base
  attr_accessible :customer_service_email_address, :customer_service_phone_number, :default_value_for_weekly_production_quota, :rbn_number
  
  validates_presence_of :aws_bucket_name, :customer_service_email_address, :customer_service_phone_number, :default_value_for_weekly_production_quota, :rbn_number, :default_currency_id
  
  belongs_to  :currency,
              :class_name => "Currency",
              :foreign_key => "default_currency_id"
  
  def ccy
    currency.currency_symbol
  end
  
end
