# Image.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class Image < ActiveRecord::Base
  attr_accessible :base_product, :bucket_name, :content_type, :file_name, :file_size, :finished_product, :uploaded_by
  
  validates_presence_of :file_name, :uploaded_by
  
  belongs_to  :uploader,
              :class_name => "User",
              :foreign_key => "uploaded_by"
  has_many    :product_images, :order => "running_order"
  has_many    :finished_product_images, :order => "running_order"
  
  def full_file_path
    # use this until AWS::S3 is implemented
    return "product_images/" + file_name
    
    # needs some more work - to include the root URL - when we have AWS:S3 working
    # return bucket_name + "/" + file_name
  end
  
end