# OptionsList.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class OptionsList < ActiveRecord::Base
  attr_accessible :name, :options, :visible_label
  
  has_many :product_categories
  has_many :products

  validates_presence_of :name, :options, :visible_label
  validates_uniqueness_of :name

end
