# PayPalTransaction.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# This code was inspired by demonstration code provided by railscasts.com;
# @ http://railscasts.com/episodes/141-paypal-basics
# @ http://railscasts.com/episodes/142-paypal-notifications
# @ http://railscasts.com/episodes/143-paypal-security
#
# Reference was also made to PayPal developer resources;
# @ https://cms.paypal.com/cms_content/US/en_US/files/developer/PP_WebsitePaymentsStandard_IntegrationGuide.pdf
# @ https://cms.paypal.com/cms_content/en_US/files/developer/PP_OrderMgmt_IntegrationGuide.pdf
#
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class PayPalTransaction < ActiveRecord::Base
  attr_accessible :amount, :currency_code, :currency_id, :paypal_transaction_id, :rest_of_the_stuff_serialised, :result_code, :shopping_cart_id
  
  belongs_to :currency
  belongs_to :shopping_cart
  
  validates_presence_of :amount, :currency_code, :currency_id, :paypal_transaction_id, :rest_of_the_stuff_serialised, :result_code, :shopping_cart_id
  validates_numericality_of :amount, :currency_id, :paypal_transaction_id
  validates_numericality_of :shopping_cart_id, :allow_nil => true
  
end
