# PayPalStatus.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# This code was inspired, but not directly prompted by or based on
# demonstration code provided by railscasts.com;
# @ http://railscasts.com/episodes/141-paypal-basics
# @ http://railscasts.com/episodes/142-paypal-notifications
# @ http://railscasts.com/episodes/143-paypal-security
#
# Reference was also made to PayPal developer resources;
# @ https://cms.paypal.com/cms_content/US/en_US/files/developer/PP_WebsitePaymentsStandard_IntegrationGuide.pdf
# @ https://cms.paypal.com/cms_content/en_US/files/developer/PP_OrderMgmt_IntegrationGuide.pdf
#
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class PayPalStatus < ActiveRecord::Base
  attr_accessible :charged_back, :description, :name, :paid_sale, :pending_authorisation
  
  validates_presence_of :name, :description
  validates_uniqueness_of :name
  
end
