# Currency.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.
#
# ==================================================================================
# NEED TO RETHINK THIS MODEL
# When you have five minutes, I'd like to hear what you have in mind.  Julian.

class ProductComponent < ActiveRecord::Base
  attr_accessible :product_id, :component_product_id, :quantity, :running_order
  
  belongs_to  :product
  
  validates_presence_of :product_id, :quantity, :running_order
  
end
