# ProductionQuantum.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ProductionQuotum < ActiveRecord::Base
  attr_accessible :start_date, :finish_date, :maximum_cakes_allowed
  
  validates_presence_of :start_date, :finish_date, :maximum_cakes_allowed
  validates_numericality_of :maximum_cakes_allowed
  validates_uniqueness_of :start_date
  
end
