# ProductCategory.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ProductCategory < ActiveRecord::Base
  attr_accessible :name, :description, :one_choice_only, :options_list_id, :running_order
  
  belongs_to :options_list
  
  validates_presence_of :name, :description, :running_order
  validates_uniqueness_of :name
  validates_numericality_of :running_order
  
  has_many :products
  
end
