# ProductImage.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ProductImage < ActiveRecord::Base
  attr_accessible :image_id, :product_id, :running_order
  
  belongs_to :image
  belongs_to :product
  
  validates_presence_of :image_id, :product_id, :running_order
  validates_numericality_of :image_id, :product_id, :running_order
  
end
