# ProductPrice.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ProductPrice < ActiveRecord::Base
  attr_accessible :start_at, :finish_at, :product_id, :currency_id, :price, :created_by, :updated_by
  
  belongs_to  :currency
  belongs_to  :product
  has_many    :shopping_cart_items
  belongs_to  :creator,
              :class_name => "User",
              :foreign_key => "created_by"
  belongs_to  :updater,
              :class_name => "User",
              :foreign_key => "updated_by"
  
  validates_presence_of :start_at, :finish_at, :product_id, :currency_id, :price, :created_by
  validates_numericality_of :product_id, :currency_id
  
end
