# ShoppingCartItem.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ShoppingCartItem < ActiveRecord::Base
  attr_accessible :shopping_cart_id, :product_id, :product_options_list_choice, :product_price_id, :quantity, :global_options_list_choice, :user_description
  
  belongs_to  :product
  belongs_to  :product_price
  belongs_to  :shopping_cart
  
  validates_presence_of :shopping_cart_id, :product_id, :product_price_id, :quantity
  validates_numericality_of :quantity, :allow_nil => true
  validates_numericality_of :shopping_cart_id, :product_id, :product_price_id

end
