# ShoppingCart.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class ShoppingCart < ActiveRecord::Base
  attr_accessible :cake_required_at, :customer_id, :general_description_from_customer, :name_to_appear_on_cake, :pay_pal_status_id, :session_id, :shopping_cart_status_id, :special_occasion, :production_quotum_id
  
  attr_reader :weekday
  
  scope :monday, where(:weekday => 1)
  scope :tuesday, where(:weekday => 2)
  scope :wednesday, where(self.cake_required_at.to_date.wday.to_i == 3)
  scope :thursday, where(:weekday => 4)
  scope :friday, where(:weekday => 5)
  scope :saturday, where(:weekday => 6)
  scope :sunday, where(:weekday => 0)
  
  belongs_to  :customer
  belongs_to  :pay_pal_status
  has_many    :pay_pal_transactions, :order => :created_at
  has_many    :shopping_cart_items, :order => :id
  belongs_to  :shopping_cart_status
  belongs_to  :production_quotum
  belongs_to  :creator,
              :class_name => "User",
              :foreign_key => "created_by"
  belongs_to  :updater,
              :class_name => "User",
              :foreign_key => "updated_by"
  
  validates_numericality_of :shopping_cart_status_id
  validates_numericality_of :customer_id
  validates_numericality_of :pay_pal_status_id
  validates_numericality_of :production_quotum_id
  
  def weekday
    return cake_required_at.to_date.wday.to_i
  end

end