# SpecialOccasion.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class SpecialOccasion < ActiveRecord::Base
  attr_accessible :name, :running_order, :visible_to_customers
  
  validates_presence_of :name, :running_order
  validates_uniqueness_of :name
  validates_numericality_of :running_order
  
  has_many :products
  has_many :finished_products
  
end
