# UserGroup.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class UserGroup < ActiveRecord::Base
  attr_accessible :description, :is_a_manager, :is_an_admin, :name
  
  has_many :users
  
  validates_presence_of :description, :name
  validates_uniqueness_of :name
  
end
