# UserSessionsController.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Code originally based on AuthLogic demonstration code 
# @ https://github.com/binarylogic/authlogic_example
#
# and on demonstration code from 
# @ http://joelgreutman.com/2011/03/13/rails-3-and-authlogic-basic-setup
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class UserSession < Authlogic::Session::Base
  #attr_accessible :session_id, :data

  logout_on_timeout true
  consecutive_failed_logins_limit 10

end