# WeeklyQuotum.rb
# 
# Class was originally generated by rails 3.2.8 
# Modified by Dan Laffan (12111619) starting 5th November 2012.
#
# Copyright © 2012, Julian Arnold and Daniel M. Laffan.  All rights reserved.
# Rights in third party code acknowledged.

class WeeklyQuotum < ActiveRecord::Base
  attr_accessible :start_date, :end_date, :quota
  
  has_many    :shopping_carts
  belongs_to  :creator,
              :class_name => "User",
              :foreign_key => "created_by"
  belongs_to  :updater,
              :class_name => "User",
              :foreign_key => "updated_by"
  
  validates_presence_of :start_date, :end_date, :quota, :created_by
  validates_uniqueness_of :start_date
  validates_numericality_of :quota
  validates_numericality_of :created_by
  validates_numericality_of :updated_by, :allow_nil => true
  
end
